transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib final_project_platform
vmap final_project_platform final_project_platform
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/final_project_platform.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_avalon_st_adapter_005.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_usb_rst.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_usb_gpx.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_timer.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_sysid_qsys_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_spi_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_sdram_pll.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_sdram.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_onchip_memory2_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0_cpu.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_nios2_gen2_0_cpu_test_bench.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_leds_pio.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_keycode.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_key.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_jtag_uart_0.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_hex_digits_pio.v}
vlog -vlog01compat -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler {C:/Users/ldm18/Desktop/ece385_final_project/acceler/spi_control.v}
vlog -vlog01compat -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler {C:/Users/ldm18/Desktop/ece385_final_project/acceler/spi_serdes.v}
vlog -vlog01compat -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler {C:/Users/ldm18/Desktop/ece385_final_project/acceler/ip.v}
vlog -vlog01compat -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/db {C:/Users/ldm18/Desktop/ece385_final_project/acceler/db/ip_altpll.v}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_irq_mapper.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_avalon_st_adapter_005_error_adapter_0.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_router_007.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_router_002.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/final_project_platform_mm_interconnect_0_router.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work final_project_platform +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules {C:/Users/ldm18/Desktop/ece385_final_project/acceler/final_project_platform/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code {C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code/VGA_controller.sv}
vlog -sv -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code {C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code/Color_Mapper.sv}
vlog -sv -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code {C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code/ball.sv}
vlog -sv -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler {C:/Users/ldm18/Desktop/ece385_final_project/acceler/HexDriver.sv}
vlog -sv -work work +incdir+C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code {C:/Users/ldm18/Desktop/ece385_final_project/acceler/385_code/final385_top.sv}

